"""Make name field required

Revision ID: 67477a9fda36
Revises: c0e724d22938
Create Date: 2025-05-28 22:20:38.719572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67477a9fda36'
down_revision = 'c0e724d22938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE \"user\" SET name = 'Unknown' WHERE name IS NULL")
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
