"""empty message

Revision ID: 881d55c007e4
Revises: ee131c89cd58
Create Date: 2025-06-13 21:34:59.563896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881d55c007e4'
down_revision = 'ee131c89cd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
