"""empty message

Revision ID: e93eda83d087
Revises: 2c27429bc60b
Create Date: 2025-05-20 21:53:35.044003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93eda83d087'
down_revision = '2c27429bc60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint('vendor_calendly_url_key', type_='unique')
        batch_op.drop_constraint('vendor_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_unique_constraint('vendor_email_key', ['email'])
        batch_op.create_unique_constraint('vendor_calendly_url_key', ['calendly_url'])

    # ### end Alembic commands ###
